// <auto-generated />
namespace TechReviewMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changingpricefromdoubletostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changingpricefromdoubletostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201702101919270_changing price from double to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
